"use client"
import { H2, H4 } from "@/components/shared/typography";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Users, Clock, Calendar, AlertTriangle, AlertCircle, PhoneCall, ChevronRight, Activity } from "lucide-react";
import Link from "next/link";
import { Badge } from "@/components/ui/badge";

export default function DoctorDashboard() {
  return (
    <div className="max-w-7xl mx-auto space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-500 pb-10">
      
      {/* Welcome & Stats Row */}
      <div className="grid grid-cols-1 lg:grid-cols-4 gap-6">
        
        {/* Welcome Block */}
        <div className="lg:col-span-2 bg-navy dark:bg-blue-950/80 rounded-[2rem] p-8 md:p-10 shadow-[0_15px_40px_-10px_rgba(10,35,66,0.3)] text-white relative overflow-hidden flex flex-col justify-center">
          <div className="absolute right-0 top-0 w-64 h-full bg-[linear-gradient(to_left,rgba(255,255,255,0.05),transparent)]" />
          <div className="relative z-10">
            <H2 className="text-white mb-3 tracking-tight">Good morning, Dr. Mithun</H2>
            <p className="text-blue-100 font-medium max-w-sm leading-relaxed mb-8">
              You have 5 appointments today and 2 new patient insights generated by AI.
            </p>
            <div className="flex items-center gap-4">
              <Badge className="bg-emerald-500 text-white border-none py-1.5 px-4 rounded-xl font-extrabold shadow-sm">
                <span className="w-2 h-2 rounded-full bg-white mr-2 animate-pulse" /> Available for Consults
              </Badge>
            </div>
          </div>
        </div>

        {/* Quick Stats */}
        <StatCard icon={<Users className="h-6 w-6 text-navy dark:text-blue-300" />} title="Total Patients" value="1,248" change="+12 this month" />
        <StatCard icon={<Clock className="h-6 w-6 text-navy dark:text-blue-300" />} title="Avg Wait Time" value="14 mins" change="-2 mins vs last week" />

      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        
        {/* Critical Alerts Pipeline */}
        <div className="lg:col-span-2 space-y-6">
          <div className="flex items-center justify-between px-1">
            <H4 className="flex items-center gap-2">
              <AlertCircle className="h-6 w-6 text-error" /> AI Actionable Insights
            </H4>
            <Button variant="ghost" className="text-navy dark:text-blue-400 font-extrabold hover:bg-slate-100 dark:hover:bg-slate-800 rounded-xl">View Pipeline</Button>
          </div>

          <div className="space-y-4">
            <AlertItem 
              name="Sarah Jenkins" 
              condition="Type 1 Diabetes" 
              alert="Continuous glucose spike > 200mg/dL for 4 hours. Recommend adjusting basal insulin." 
              severity="critical"
              time="10 mins ago"
            />
            <AlertItem 
              name="Robert Fox" 
              condition="Hypertension" 
              alert="Missed Lisinopril dose for 3 consecutive days." 
              severity="high"
              time="1 hour ago"
            />
            <AlertItem 
              name="Eleanor Pence" 
              condition="Anxiety" 
              alert="PHQ-9 score increased by 4 points in recent assessment. Flagged for early review." 
              severity="medium"
              time="3 hours ago"
            />
          </div>
        </div>

        {/* Today's Schedule */}
        <div className="space-y-6">
          <Card className="border-slate-200 dark:border-slate-800 shadow-[0_8px_30px_rgb(0,0,0,0.04)] dark:shadow-none rounded-[2rem] bg-white dark:bg-slate-900 overflow-hidden h-full flex flex-col">
            <div className="p-6 md:p-8 border-b border-slate-100 dark:border-slate-800 flex justify-between items-center bg-slate-50/50 dark:bg-slate-900/50 shrink-0">
              <H4>Today's Schedule</H4>
              <Button size="icon" variant="ghost" className="h-10 w-10 text-navy dark:text-blue-400 bg-slate-100 dark:bg-slate-800 rounded-xl transition-colors">
                <Calendar className="h-5 w-5" />
              </Button>
            </div>
            <CardContent className="p-0 flex-1 overflow-y-auto">
              <div className="divide-y divide-slate-100 dark:divide-slate-800">
                <ScheduleItem time="10:00 AM" name="Michael T." type="Video Consult" active={true} />
                <ScheduleItem time="11:30 AM" name="Sarah Jenkins" type="In-Person" active={false} />
                <ScheduleItem time="02:00 PM" name="David Kim" type="Video Consult" active={false} />
                <ScheduleItem time="04:15 PM" name="Amanda R." type="Report Review" active={false} />
              </div>
            </CardContent>
            <div className="p-5 border-t border-slate-100 dark:border-slate-800 shrink-0 bg-slate-50/50 dark:bg-slate-900/50">
               <Link href="/doctor/schedule" className="w-full h-12 bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 hover:border-navy dark:hover:border-blue-500 shadow-sm text-navy dark:text-slate-200 font-bold rounded-xl flex items-center justify-center transition-colors">
                 Open Full Calendar
               </Link>
            </div>
          </Card>
        </div>

      </div>
    </div>
  );
}

function StatCard({ icon, title, value, change }: any) {
  return (
    <Card className="border-slate-200 dark:border-slate-800 shadow-sm hover:shadow-md transition-shadow rounded-[2rem] bg-white dark:bg-slate-900 p-8 flex flex-col justify-center">
      <div className="flex justify-between items-start mb-4">
        <div className="p-3 bg-blue-50 dark:bg-blue-900/30 rounded-2xl shadow-inner border border-blue-100/50 dark:border-blue-800/50">
          {icon}
        </div>
      </div>
      <div>
        <p className="text-sm font-bold text-text-secondary dark:text-slate-400 mb-1">{title}</p>
        <h3 className="text-3xl font-black text-navy dark:text-slate-100 tracking-tight">{value}</h3>
      </div>
      <div className="mt-5 pt-4 border-t border-slate-100 dark:border-slate-800">
        <span className="text-xs font-extrabold text-success tracking-wide uppercase">{change}</span>
      </div>
    </Card>
  );
}

function AlertItem({ name, condition, alert, severity, time }: any) {
  const getSeverityColors = () => {
    if (severity === 'critical') return 'bg-error text-white shadow-[0_5px_15px_-3px_rgba(231,76,60,0.4)] border-transparent';
    if (severity === 'high') return 'bg-warning text-white shadow-[0_5px_15px_-3px_rgba(243,156,18,0.4)] border-transparent';
    return 'bg-blue-50 text-blue-800 dark:bg-blue-900/30 dark:text-blue-300 border border-blue-100 dark:border-blue-800/50';
  };

  const getIcon = () => {
    if (severity === 'critical') return <AlertTriangle className="h-6 w-6 text-white" />;
    if (severity === 'high') return <Activity className="h-6 w-6 text-white" />;
    return <AlertCircle className="h-6 w-6 text-blue-500 dark:text-blue-400" />;
  };

  return (
    <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-[1.5rem] p-6 lg:p-7 shadow-sm hover:shadow-md transition-shadow flex flex-col sm:flex-row sm:items-center gap-6 cursor-pointer group">
      
      <div className={`p-4 rounded-2xl flex items-center justify-center shrink-0 transition-transform group-hover:scale-105 ${getSeverityColors()}`}>
        {getIcon()}
      </div>

      <div className="flex-1 min-w-0">
        <div className="flex items-center gap-3 mb-2">
          <h4 className="font-extrabold text-lg text-foreground tracking-tight truncate">{name}</h4>
          <Badge variant="outline" className="text-[10px] uppercase font-black tracking-widest text-slate-500 border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-800/80">{condition}</Badge>
        </div>
        <p className="text-sm font-medium text-text-secondary dark:text-slate-300 leading-relaxed mb-3">
          {alert}
        </p>
        <span className="text-xs font-bold text-slate-400 uppercase tracking-widest">{time}</span>
      </div>

      <div className="shrink-0 self-start sm:self-center hidden md:block">
        <Button variant="outline" size="sm" className="h-12 px-6 rounded-xl font-bold border-slate-200 dark:border-slate-700 hover:bg-slate-50 dark:hover:bg-slate-800">
          Review File
        </Button>
      </div>

    </div>
  );
}

function ScheduleItem({ time, name, type, active }: any) {
  return (
    <div className={`p-6 flex items-center justify-between transition-colors cursor-pointer border-l-4 relative overflow-hidden ${active ? 'border-emerald-500 bg-emerald-50/50 dark:bg-emerald-900/10' : 'border-transparent hover:bg-slate-50 dark:hover:bg-slate-800/40'}`}>
      {active && <div className="absolute left-0 top-0 w-32 h-full bg-[linear-gradient(to_right,rgba(16,185,129,0.05),transparent)]" />}
      <div className="flex items-center gap-5 relative z-10">
        <div className="text-center w-16 shrink-0 bg-slate-50 dark:bg-slate-800 rounded-xl py-2 px-1 border border-slate-100 dark:border-slate-700 shadow-inner">
          <p className={`font-black text-base tracking-tight ${active ? 'text-emerald-600 dark:text-emerald-400' : 'text-slate-600 dark:text-slate-400'}`}>
            {time.split(' ')[0]}
          </p>
          <p className={`text-[10px] font-black uppercase tracking-widest mt-0.5 ${active ? 'text-emerald-600/70 dark:text-emerald-400/70' : 'text-slate-400'}`}>{time.split(' ')[1]}</p>
        </div>
        <div>
          <p className={`font-extrabold text-lg mb-1 tracking-tight ${active ? 'text-navy dark:text-slate-100' : 'text-foreground'}`}>{name}</p>
          <div className="flex items-center gap-1.5">
            {type.includes('Video') && <PhoneCall className="h-4 w-4 text-slate-400" />}
            <span className="text-xs font-bold text-slate-500 uppercase tracking-widest">{type}</span>
          </div>
        </div>
      </div>
      {active && (
        <Button size="sm" className="bg-emerald-500 hover:bg-emerald-600 text-white font-bold h-10 rounded-xl px-5 shadow-[0_5px_15px_-3px_rgba(16,185,129,0.4)] relative z-10 transition-transform active:scale-95">
          <span className="w-1.5 h-1.5 rounded-full bg-white mr-2 animate-ping" /> Join
        </Button>
      )}
    </div>
  );
}
